[package]
name = "sennoza/line"
version = "0.0.2-test"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]