[package]
name = "sennoza/line"
description = "A simply stupid remote wrapper for Roblox"
version = "0.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = [
	"Sennoza"
]
exclude = [
	"docs",
	"media",
	"Packages",
]

[dependencies]